#!/usr/bin/env python
import sys
import json
import os.path

def generate_unique_key(data, key):
    pos=1
    while data.get(f"{key}_{pos}"):
        pos += 1
    return f"{key}_{pos}"

def addToJsonFile(filename, key, value):
    data = {}
    if os.path.isfile(filename):
        f = open(filename)
        data = json.load(f)
        f.close()

    if data.get(key):
        key = generate_unique_key(data, key)

    data[key] = value

    # for debugging
    # data['translation_file'] = filename

    # save changed json file
    with open(filename, "w") as outfile:
        json.dump(data, outfile, indent=4, sort_keys=True)


if __name__ == '__main__':
    if len(sys.argv) < 4:
        print(f"USAGE: {sys.argv[0]} <json_file> <key> <value>")
    else:
        json_file = sys.argv[1]
        key = sys.argv[2]
        value = sys.argv[3]
        addToJsonFile(json_file, key, value)
